export default interface Author  {
  photo: {node:{mediaItemUrl: string}} ,
  firstName: string ,
  lastName: string ,
  slogan_en : string,
  slogan_es : string,
  slogan : string,
  email: string ,
  ubication: string ,
  phonenumber: string,
  role: string ,
  instagram_url?: string | null,
  facebook_url?: string | null,
  twitter_url?: string | null,
  linkedin_url?: string | null,
  stackoverflow_url?: string | null,
  dribbble_url?: string | null,
  github_url?: string | null,
  pinterest_url?: string | null,
  twitch_url?: string | null,
  youtube_url?: string | null,
  availableForWork?: boolean | null,
  brief_introduction?: string | null,
  brief_introduction_en?: string | null,
  brief_introduction_es?: string | null,
  achievements?: string | null,
  achievements_en?: string | null,
  achievements_es?: string | null,
  services?: string[] | null,
  services_en?: string[] | null,
  services_es?: string[] | null,
  tools?: string[] | null
}
