export default interface Author  {
  image: string ,
  first_name: string ,
  last_name: string ,
  email: string ,
  phone_number: string,
  role: string ,
  ubication: string,
  instagram_url?: string | null,
  facebook_url?: string | null,
  twitter_url?: string | null,
  linkedin_url?: string | null,
  stackoverflow_url?: string | null,
  dribbble_url?: string | null,
  github_url?: string | null,
  pinterest_url?: string | null,
  twitch_url?: string | null,
  youtbe_url?: string | null,
}
