export default interface Experience {
  initYear: Date,
  endYear: Date,
  position: string,
  position_en: string,
  position_es: string,
  companyName: string,
  details: string,
  details_en: string,
  details_es: string,
  link: string,
  present: boolean,
  content: string,
  content_en: string,
  content_es: string,
}
