export default interface Project {
  name: string,
  type: string,
  thumbnail: {node:{mediaItemUrl: string}},
  content: string,
  slug:string,
  project_url: string,
  excerpt: string,
  id: string,
  title: string,
  featuredImage: {node:{mediaItemUrl: string,srcSet: string, sizes: string, altText:string}},
  status: string,
  date: Date,
  modified: Date,
}
