import type { Testimonial } from "@/types";

export default interface Project {
  name: string,
  type: string,
  thumbnail: {node:{mediaItemUrl: string}},
  image_1 : {node:{mediaItemUrl: string}},
  content: string,
  slug:string,
  project_url: string,
  excerpt: string,
  id: string,
  title: string,
  status: string,
  date: Date,
  draft: boolean,
  modified: Date,
  tags: string[],
  goals: string,
  tools: string,
  solutions: string,
  background: string ,
  conclusion: string ,
  testimonial : Testimonial,
  role : string ,
  init_year: Date,
  end_year: Date | null, 
  description: string,
  present: boolean | null,
}
