import type { Testimonial } from "@/types";

export default interface Project {
  name: string,
  name_en: string,
  name_es: string,
  type: string,
  type_en: string,
  type_es: string,
  thumbnail: {node:{mediaItemUrl: string}},
  image1 : {node:{mediaItemUrl: string}},
  content: string,
  slug:string,
  preview_url: {url:string},
  excerpt: string,
  id: string,
  title: string,
  status: string,
  date: Date,
  draft: boolean,
  modified: Date,
  tags: string[],
  goals: string,
  goals_en: string,
  goals_es: string,
  tools: string,
  tools_en: string,
  tools_es: string,
  solutions: string,
  solutions_en: string,
  solutions_es: string,
  background_en: string ,
  background_es: string ,
  background: string ,
  conclusion: string ,
  conclusion_en: string ,
  conclusion_es: string ,
  testimonial : {edges: {node:{testimonialItem: Testimonial}}[]} ,
  role : string ,
  initYear: Date,
  endYear: Date | null, 
  description: string,
  description_en: string,
  description_es: string,
  present: boolean | null,
}
