import type { Testimonial } from "@/types";

export default interface Project {
  name: string,
  type: string,
  thumbnail: string,
  image1 : string,
  content: string,
  slug:string,
  preview_url: string,
  excerpt: string,
  id: string,
  title: string,
  status: string,
  date: Date,
  draft: boolean,
  modified: Date,
  tags: string[],
  goals: string,
  tools: string,
  solutions: string,
  background: string ,
  conclusion: string ,
  testimonial : Testimonial,
  role : string ,
  initYear: Date,
  endYear: Date | null, 
  description: string,
  present: boolean | null,
}
