export default interface StoreItem {
  name: string,
  name_en: string,
  name_es: string,
  type: string,
  type_en: string,
  type_es: string,
  thumbnail: {node:{mediaItemUrl: string}},
  price: number,
  currency: string,
  content: string,
  content_en: string,
  content_es: string,
  draft: boolean,
  link: string,
  slug: string,
  brief_description: string,
  items_en:string ,
  items_es:string ,
  items:string ,
  brief_description_en: string,
  brief_description_es: string,
  description: string,
  description_en: string,
  description_es: string,
  status: string,
  date: Date,
  modified: Date,
  id: string,
  buy_link: string,
  preview_link: string,
  image_1? :  {node:{mediaItemUrl: string}},
  image_2? :  {node:{mediaItemUrl: string}},
  image_3? :  {node:{mediaItemUrl: string}},
  image_4? :  {node:{mediaItemUrl: string}},

}
