export default interface StoreItem {
  name: string,
  type: string,
  thumbnail: string,
  price: number,
  currency: string,
  content: string,
  draft: boolean,
  link: string,
  slug: string,
  brief_description: string,
  items:string ,
  description: string,
  status: string,
  date: Date,
  modified: Date,
  id: string,
  buy_link: string,
  preview_link: string,
  image_1? :  string,
  image_2? : string,
  image_3? : string,
  image_4? : string,

}
